1.ndarry

特性

多维性

In [1]:
import numpy as np

In [3]:
arr = np.array(5)#0维度ndarray数组
print(arr)
print('arr的维度',arr.ndim)    #arr

5
arr的维度 0


In [4]:
arr = np.array([1,2,3])#1维度ndarray数组
print(arr)
print('arr的维度',arr.ndim)    #arr

[1 2 3]
arr的维度 1


In [6]:
arr = np.array([[1,2,3],[4,5,6]]
               )#2维度ndarray数组
print(arr)
print('arr的维度',arr.ndim)    #arr

[[1 2 3]
 [4 5 6]]
arr的维度 2


()内每一个[]是为一组，0维是单个，1维是一个多个元素作为一个整体，2维是多个1维元素作为一个整体

同质性

In [7]:
arr = np.array([1,'hello'])#不同数据类型会被转变为相同类型
print(arr)

['1' 'hello']


In [8]:
arr = np.array([1,2.5])#1会被转换成浮点数但是1的零会被省略掉
print(arr)

[1.  2.5]





2.ndarray
属性

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状',arr.shape)
print('数据的维度',arr.ndim)
print('元素个数',arr.size)
print('元素的数据类型',arr.dtype)
print('元素的转置换',arr.T)


[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
数据的维度 2
元素个数 6
元素的数据类型 int64
元素的转置换 [[1 4]
 [2 5]
 [3 6]]


3ndarry的创建

In [9]:
#基础的创建方法
list1 = [1,2,3]
arr = np.array([1,2,3])
print(arr.ndim)
print(arr)
print(list1)

1
[1 2 3]
[1, 2, 3]


In [10]:
#copy
arr1 = np.copy(arr)
print(arr1)

[1 2 3]


In [11]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [14]:
#全1
arr = np.ones((5,3),dtype='int64')
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
#未初始化
arr = np.empty((4,2))
print(arr)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 9.45752306e-308]
 [1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306]]


In [16]:
arr = np.full((3,4),2025)
print(arr)#第二个参数是要填充的数

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [17]:
#等差数列
arr = np.arange(1,11,2)#结尾个数是n-1，第三个数字是步长
print(arr)

[1 3 5 7 9]


In [19]:
#等间隔数列
arr = np.linspace(1,10,5,dtype = int)#结尾个数是n，第三个数字是几等分,第四个是强制类型，line space
print(arr)

[ 1  3  5  7 10]


In [23]:
from numpy import logspace

#等对数数列
arr = logspace(0,10,5,base=2,dtype = int)#区间是第一个数字到最后一个数字n，第3个数字是平均区间取多少个点，就是前三个数字决定取出等分的间隔作为幂，第四个数字是底
print(arr)

[   1    5   32  181 1024]


In [24]:
#特殊矩阵
#单位矩阵，主对角线数字为1，其他数字为0
arr = np.eye(3,4,dtype = int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [25]:
#对角矩阵，只有主对角线数字非0
arr = np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [28]:
#随机数组生成
#生成0-1之间的均匀随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.3574695  0.90295483 0.48359591]
 [0.26766334 0.94740161 0.15578271]]


In [29]:
#生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))#3-6之间，2行3列
print(arr)

[[3.44689108 3.69299418 4.67301916]
 [5.18067453 5.53911921 5.92127753]]


In [30]:
#生成指定范围区间的随机整数
arr = np.random.randint(3,30,(2,3))
print(arr)

[[24 23 11]
 [15 25 17]]


In [34]:
#生成随机数列(正态分布)
arr = np.random.randn(2,3)
print(arr)

[[-0.40680597 -0.21307322  0.00932901]
 [ 1.20864458  1.00291631 -0.10144808]]


In [37]:
#设置随机种子
np.random.seed(200)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[1 5 8 7 9]
 [2 8 4 2 8]]


In [5]:
#ndarray的数据类型
#布尔 整数 浮点数 复述
arr = np.array([1,0,0,1,0],dtype= np.int8)
print(arr)
arr = np.array([1,0,0,1,0],dtype= bool)
print(arr)

[1 0 0 1 0]
[ True False False  True False]


5.索引与切片

In [6]:
#一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

[98 86  3 86 29 34 26 46 39 64 14 74 23 95 40  2 28 55 68 48]


In [15]:
print(arr[10])
print(arr[:])#获取全部
print(arr[2:5])#数组第一个位置是0，最后一个位置是n-1
print(arr[arr>10])#bool索引arr数组中大于10的数
print(arr[(arr>10) & (arr<50)])#在涉及条件判断时，逻辑关系往往也能使用，或且非,多个元素记得加个括号
print(arr[slice(2,5)])#同print(arr[2:5])#数组第一个位置是0，最后一个位置是n-1
print(arr[slice(0,7,2)])#slice切片函数可以使用步长切割数组

14
[98 86  3 86 29 34 26 46 39 64 14 74 23 95 40  2 28 55 68 48]
[ 3 86 29]
[98 86 86 29 34 26 46 39 64 14 74 23 95 40 28 55 68 48]
[29 34 26 46 39 14 23 40 28 48]
[ 3 86 29]
[98  3 29 26]


In [16]:
#二维数组
arr = np.random.randint(1,100,(4,8))#四行八列
print(arr)

[[19 36 49 93 53 61 18 66]
 [39 42 26  5 46 57 89 62]
 [36 91 85  3 46 53 14 59]
 [82  1 48 11 24 88 60 17]]


In [34]:
print(arr[1,3])#切片规则开始和数组的开始索引一样，但是结束的时候数组是n-1，切片是n，但是切片的结束是开区间
print(arr[1:3,3])#第2行和第三行，第3列，要切片在哪，哪就要:，结束就记忆我要取到第几行列就写几
print(arr[2:4,0:1])#第3行第四行，第一列，
print(arr[arr>50])
print(arr[2][arr[2] < 30])#我只要筛选第二行的,就类似c的arr[][]
print(arr[arr[:,3]<20,])#
print(arr[arr[:,3]<20,3])#我只要第四列小于20的,潜台词，所有行的第四列

5
[5 3]
[[36]
 [82]]
[93 53 61 66 57 89 62 91 85 53 59 82 88 60]
[ 3 14]
[[39 42 26  5 46 57 89 62]
 [36 91 85  3 46 53 14 59]
 [82  1 48 11 24 88 60 17]]
[ 5  3 11]


ndarray的计算

In [36]:
#算术运算
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**3)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[ 1  8 27]


In [38]:
#列表
c = [1,2,3]
d = [4,5,6]
print(c+d)#放到末尾
for i in range (len(c)):
    d[i] = c[i] + d[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [40]:
#算术运算，二维
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [42]:
#数组与标量的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [45]:
#广播机制
#同一维度13，31，处理数据尽量统一格式，这个了解就好
a = np.array([1,2,3])#一行3列
b = np.array([[4],[5],[6]])#3行一列
print(a+b)
print(a-b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]


In [46]:
#矩阵的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])#用到再学
print(a*b)

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]


numpy常用函数
基本数学


In [5]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [7]:
#计算指数
print(np.exp(1))#e的多少次方，这个是一次方
print(np.exp(0))

2.718281828459045
1.0


In [8]:
#计算自然对数
print(np.log(2.71))#lnx
print(np.log(2))

0.9969486348916096
0.6931471805599453


In [10]:
#计算三角函数的值
print(np.sin(1))
print(np.sin(np.pi/2))
print(np.cos(np.pi))

0.8414709848078965
1.0
-1.0


In [11]:
#计算绝对值
arr = np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [12]:
#计算a的b次幂
print(np.power(arr,3))

[ -1   1   8 -27]


In [14]:
#四舍五入
print(np.round([3.2,4.5,8.1,9.6]))

[ 3.  4.  8. 10.]


In [15]:
#向上取整，向下取整
arr = np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [17]:
#检查缺失值
np.isnan([1,2,np.nan,3])#np.nan代表缺失值

array([False, False,  True, False])

统计函数
求和，计算平均值，计算中位数，标准差，方差

查找最大值，最小值

计算分位数，累计和，累计差

In [19]:
arr = np.random.randint(1,20,8)
print(arr)

[10 10  6  2  6  3 15 13]


In [21]:
#求和
print(np.sum([1,2,3]))

6


In [23]:
#计算平均值
print(np.mean([1,2,3],dtype = int))

2


In [26]:
#计算中位数
print(np.median([4,2,1000]))#会由大到小找出中间的，不是数组中间的

4.0


In [30]:
#计算标准差，方差
#1,2,3的平均值是2
#（（1-2）**2+（2-2）**2+（3-2）**2）/3=0.666，而标准差就是开个sqrt
print(np.var([1,2,3]))#方差
print(np.std([1,2,3]))#标准差，越小越稳定
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

0.6666666666666666
0.816496580927726
1.375
1.375
0.234375
2.484375


In [31]:
#计算最大值，最小值
print(arr)
print(np.max(arr))
print(np.min(arr))

[10 10  6  2  6  3 15 13]
15
2


In [35]:
#分位数
#中位数
#--------------------------
#1      2          3      4
#1           2            3
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,50))#排在第50%的数字
print(np.percentile(arr,25))#0.25*3=0.75，单位数轴每1%的值(47-44)*0.75=2.25+44=46.25,   几等分和数轴有多少间隔就是多少个元素有关而不是数值有关

2.0
2.5
[44 47 64 67]
55.5
55.5
46.25


In [36]:
#累计和，累计积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))#每一位置的前缀和
print(np.cumprod(arr))#每一位置的积

6
[1 3 6]
[1 2 6]


比较函数
比较是否大于，小于，等于，或与非

In [40]:
#是否大于
print(np.greater([3,5,3,7,6],4))
#是否小于
print(np.less([3,5,3,7,6],4))
#是否等于
print(np.equal([3,4,5],[4,4,4]))

[False  True False  True  True]
[ True False  True False False]
[False  True False]


In [41]:
#或与非
print(np.logical_and([0,0],[1,1]))#这里的0，1是false和true
print(np.logical_or([0,0],[1,1]))
print(np.logical_not([1,0]))

[False False]
[ True  True]
[False  True]


In [42]:
#检查元素是否至少有一个元素为True
print(np.any([0,0,0,0]))
#检查元素是否全部为true
print(np.all([1,1]))


False
True


In [44]:
#自定义条件
#print（np.where(条件，符合条件，不符合条件)）
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))#条件，符合条件的保存原样，不符合就为0

[1 2 0 0 0]


In [45]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,1,0))

[1 1 0 0 0]


In [47]:
score = np.random.randint(50,100,20)
print(score)
print(np.where(score>=60,'及格','不及格'))

[63 58 59 70 66 55 65 97 50 68 85 74 99 79 69 69 64 89 82 51]
['及格' '不及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '不及格']


In [50]:
print(np.where(#这里的不符合条件就进行np.where（，，）
    score<60,'不及格',np.where(
        score<80,'良好',np.where(
            score<90,'优秀',np.where(
                score<=100,'完美','异常'
            )
        )
    )
))

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '完美' '不及格' '良好' '优秀' '良好' '完美' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


In [53]:
print(np.select([score>=80,(score>=60)&(score<80),score<60],['优秀','良好','不及格'],['未知']))
#三个要素缺一不可，条件，符合就输出什么，不符合输出什么

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '优秀' '不及格' '良好' '优秀' '良好' '优秀' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


排序函数

In [57]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.sort(arr))
print(arr)
print(np.argsort(arr))#按大小排序的数组后的每一个原始数组对应数字的索引
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [58]:
#去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [60]:
#两个数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [63]:
#数组分割
print(np.split(arr,4))#arr20个元素，切割成4份，每个5个元素
print(np.split(arr,[6,12,18]))#第二个参数是从哪里开始切割，第n就是从第n个位置开始切，知识在索引与切片哪里，索引是左必又开，数组从0开始计算，所以这里的6就相当于数组arr的[5]，直观理解就是写哪个数字就切多少个元素，这里是在第六个元素，第12个元素开始切，切割位置在6的左边12的左边，切开之后就是分段了

[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32), array([71, 89, 89, 13, 59], dtype=int32), array([66, 40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [64]:
#调整数组的形状
print(np.reshape(arr,[5,4]))#切割成5行四列，元素数量要对得上

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]


综合练习


In [4]:
#1
temps = np.array([28,30,29,31,32,30,29])
print(temps)
print('%.3f'%np.mean(temps))
print(np.max(temps))
print(np.min(temps))
count = 0
for i in temps:
    if i > 30:
        count += 1
print("超过30度的天数:", count)

[28 30 29 31 32 30 29]
29.857
32
28
超过30度的天数: 2


In [6]:
#2
score = np.array([85,90,78,92,88])
print(score)
print('平均分',np.mean(score))
print('中位数',np.median(score))
print('标准差 %.3f'%np.std(score))
print(score/10)#对np数组来说，能直接被标量处理

[85 90 78 92 88]
平均分 86.6
中位数 88.0
标准差 4.883
[8.5 9.  7.8 9.2 8.8]


In [8]:
#3
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)#点积，用到再学

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [22]:
#4
arr = np.random.randint(0,10,[3,4])#随机生成的终点是取不到10的
print(arr)
print('每列最大值',np.max(arr,axis=0))#0是列，或者你往切片考虑
arr1 = []
for i in range(arr.shape[1]):  # 此时 i 依次变成 0, 1, 2,    shape[0]是行数，shape[1]是列数，range就是3，在这里，这里只是相当于说：我要遍历每一列
    current_col = arr[:,i]#单独把每一列换成一维数组 : 每一行，每一列的i，i=1时095，i＝2时196，i=3时985，i=4时355，
    max_col = np.max(current_col)#095里面找，在一维数组里面找
    print(f'第{i+1}列最大值:{max_col}')#f格式字符串，{}花括号表示要用到的变量不是字符  等价于for i in range(arr.shape[1]): print(np.max(arr[:, i]))

for i in range(arr.shape[0]):
    print(f'第{i+1}行最小值：{np.min(arr[i,:])}')

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):#np的遍历下标就这样，把下标拿出来，就能套进数组
        if (arr[i][j]%2) != 0:
            arr[i][j]=-1
print(arr)

[[1 7 3 8]
 [7 1 2 3]
 [5 0 7 1]]
每列最大值 [7 7 7 8]
第1列最大值:7
第2列最大值:7
第3列最大值:7
第4列最大值:8
第1行最小值：1
第2行最小值：1
第3行最小值：0
[[-1 -1 -1  8]
 [-1 -1  2 -1]
 [-1  0 -1 -1]]


In [35]:
#5
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
arr1 = np.zeros((3,4),dtype= int)#声明容器
index = 0
for i in range(3):
    for j in range(4):
        arr1[i][j]=arr[index]
        index+=1

print(arr1)

#计算每行的和
for i in range(3):
    sum_hang = 0
    for j in range(4):
        sum_hang += arr1[i][j]
    print(f'第{i+1}行最大值：{sum_hang}')

#计算每列的平均值
for i in range(4):#这里ij反转了
    sum_lie = 0
    for j in range(3):
       sum_lie += arr1[j][i]
    print(f'第{i+1}列平均值：{sum_lie/3}')

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
第1行最大值：10
第2行最大值：26
第3行最大值：42
第1列平均值：5.0
第2列平均值：6.0
第3列平均值：7.0
第4列平均值：8.0


In [39]:
#6
arr = np.random.randint(0,20,(5,5))#最大不到20
print(arr)
arr1 = np.zeros((5,5),dtype= int)
for i in range(5):
    for j in range(5):
        if arr[i][j] >10:
          arr1[i][j]=arr[i][j]
          print(f'第{i+1}行第{j+1}列：{arr1[i][j]}')

for i in range(5):
    for j in range(5):
        if arr[i][j] >10:
            arr[i][j]=0
print(arr)

[[ 4 10  7 15 10]
 [17  0 11  4 19]
 [11  9  0  0 15]
 [ 4 14  5 13  2]
 [ 0 16 19 19  9]]
第1行第4列：15
第2行第1列：17
第2行第3列：11
第2行第5列：19
第3行第1列：11
第3行第5列：15
第4行第2列：14
第4行第4列：13
第5行第2列：16
第5行第3列：19
第5行第4列：19
[[ 4 10  7  0 10]
 [ 0  0  0  4  0]
 [ 0  9  0  0  0]
 [ 4  0  5  0  2]
 [ 0  0  0  0  9]]


In [51]:
#7
arr = np.array([120,135,110,125,130,140])
print(f'总和{np.sum(arr)}')
print(f'方差{np.var(arr):.3f}')
max = 0
min = 10000000000000000
max_month = 0
min_month = 0
for i in range(len(arr)):
    cur=arr[i]
    if cur>max:
        max=cur
        max_month=i
    if cur<min:
        min=cur
        min_month=i
print(f'销售额最大值为{max}，{max_month}月,       最小值{min}，{min_month}月')

总和760
方差97.222
销售额最大值为140，5月,       最小值110，2月


In [52]:
#8
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate([A,B])
print(C)
print(np.reshape(C,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [56]:
#9
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))#找出唯一数字并排序
arr = np.array([2, 1, 2, 3, 1, 4, 3])
arr.sort()  # 第一步：排序 [1 1 2 2 3 3 4]
print("排序后:", arr)

unique_elements = []
counts = []
'''
# 第二步：初始化
current_val = arr[0]
current_count = 1

# 第三步：从第二个数开始遍历
for i in range(1, len(arr)):
    if arr[i] == current_val:
        current_count += 1
    else:
        # 发生不一致，结算上一个数
        unique_elements.append(int(current_val))
        counts.append(current_count)
        # 重新开始计数
        current_val = arr[i]
        current_count = 1

# 第四步：收尾（把最后一个数存进去）
unique_elements.append(int(current_val))
counts.append(current_count)

print("唯一值:", unique_elements)
print("出现次数:", counts)
'''
unique_elements, counts = np.unique(arr, return_counts=True)

print("唯一值:", unique_elements)
print("出现次数:", counts)

[1 2 3 4]
排序后: [1 1 2 2 3 3 4]
唯一值: [1 2 3 4]
出现次数: [2 2 2 1]
